FROM microsoft/dotnet:latest

#COPY src/TodoApiCore/bin/Debug/netcoreapp1.0/publish /root/
#WORKDIR /root/

#RUN ["dotnet", "restore"]
#RUN ["dotnet", "build"]

#EXPOSE 5000/tcp
#ENV ASPNETCORE_URLS http://*:5000

#ENTRYPOINT dotnet /root/TodoApiCore.dll

COPY . /app
WORKDIR /app

RUN ["dotnet", "restore"]
RUN ["dotnet", "build"]

EXPOSE 5000/tcp
ENV ASPNETCORE_URLS http://*:5000

ENTRYPOINT ["dotnet", "run", "--server.urls", "http://*:5000"]