version: '2'

services:
    apicoreapp:
        build:
            context: .
            dockerfile: DockerFile
        ports:
            - "8080:5000"
        networks:
            - apicore-network

    redisdb:
        image: redis:latest
        networks:
            - apicore-network
        container_name: redis

    wso2am191:
        image: isim/wso2apim:latest
        networks:
            - apicore-network
        container_name: wso2am191
        ports:
            - "9443:9443"
            - "9736:9736"
            - "8243:8243"
            - "8280:8280"
            - "10397:10397"
            - "7711:7711"
networks:
    apicore-network:
        driver: bridge
